name: Publish Python  🐍 distribution 📦 to PyPI and TestPyPI

on: push

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
    - name: Install dependencies with Poetry
      run: |
        poetry install
    - name: Check code formatting with Black
      run: |
        poetry run black --check .
    - name: Run tests with pytest
      run: |
        poetry run pytest
    - name: Build a binary wheel and a source tarball
      run: |
        poetry build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-dev

      - name: Build the package
        run: |
          poetry build

      - name: Upload package to PyPI
        env:
          POETRY_HTTP_BASIC_FOO_USERNAME: __token__
          POETRY_HTTP_BASIC_FOO_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --verbose